/**
 * hero-data.js — Список всех героев с базовыми характеристиками.
 * Используется на страницах: heroes.html, compare.html, глобальный поиск.
 * Данные из карточек героев. Поля с null — ждут заполнения.
 */
var HEROES_DATA = [
    // Сила
    { name: 'Адмирал', title: 'Морской воин', attr: 'strength', role: 'tank', roleName: 'Танк', heroId: 'admiral', image: 'admiral',
      strBase: 28, strGain: 3, agiBase: 14, agiGain: 2, intBase: 18, intGain: 2,
      hp: 650, mp: 150, atk: 25, def: 2, atkSpeed: 2.0, hpRegen: 1, mpRegen: 0.01, speed: 290, range: 150 },
    { name: 'Друид', title: 'Хранитель природы', attr: 'strength', role: 'support', roleName: 'Помошник', heroId: 'druid', image: 'druid',
      strBase: 25, strGain: 3, agiBase: 12, agiGain: 2, intBase: 23, intGain: 2,
      hp: 660, mp: 150, atk: 20, def: 2, atkSpeed: 2.0, hpRegen: 4, mpRegen: 0.01, speed: 290, range: 150 },
    { name: 'Киборг', title: 'Механический воин', attr: 'strength', role: 'tank', roleName: 'Танк', heroId: 'cyborg', image: 'cyborg',
      strBase: 20, strGain: 3, agiBase: 16, agiGain: 2, intBase: 24, intGain: 2,
      hp: 650, mp: 150, atk: 25, def: 2, atkSpeed: 2.0, hpRegen: 1, mpRegen: 0.01, speed: 300, range: 150 },
    { name: 'Паладин', title: 'Святой рыцарь', attr: 'strength', role: 'tank', roleName: 'Танк', heroId: 'paladin', image: 'paladin',
      strBase: 24, strGain: 3, agiBase: 13, agiGain: 2, intBase: 23, intGain: 2,
      hp: 800, mp: 150, atk: 30, def: 2, atkSpeed: 2.0, hpRegen: 2, mpRegen: 0.01, speed: 280, range: 150 },
    { name: 'Король гор', title: 'Тан', attr: 'strength', role: 'tank', roleName: 'Танк', heroId: 'mountainking', image: 'mountainking', wip: true,
      strBase: 24, strGain: 3, agiBase: 11, agiGain: 1.2, intBase: 15, intGain: 1.5,
      hp: null, mp: null, atk: null, def: null, atkSpeed: null, hpRegen: null, mpRegen: 0.01, speed: 290, range: 150 },
    { name: 'Пожиратель душ', title: 'Голод Пустоты', attr: 'strength', role: 'tank', roleName: 'Танк', heroId: 'souleater', image: 'souleater', unique: true, wip: true,
      strBase: 26, strGain: 3.4, agiBase: 12, agiGain: 1.2, intBase: 14, intGain: 1.4,
      hp: null, mp: null, atk: null, def: null, atkSpeed: null, hpRegen: null, mpRegen: 0.01, speed: 295, range: 150 },
    { name: 'Огненный страж', title: 'Элементаль пламени', attr: 'strength', role: 'tank', roleName: 'Танк', heroId: 'flamewarden', image: 'flamewarden', unique: true, wip: true,
      strBase: 27, strGain: 3, agiBase: 11, agiGain: 1.1, intBase: 15, intGain: 1.6,
      hp: null, mp: null, atk: null, def: null, atkSpeed: null, hpRegen: null, mpRegen: 0.01, speed: 285, range: 150 },
    { name: 'Друид-Медведь', title: 'Страж леса', attr: 'strength', role: 'tank', roleName: 'Танк', heroId: 'druidbear', image: 'druidbear', unique: true, wip: true,
      strBase: 22, strGain: 2.8, agiBase: 14, agiGain: 1.5, intBase: 16, intGain: 1.8,
      hp: null, mp: null, atk: null, def: null, atkSpeed: null, hpRegen: null, mpRegen: 0.01, speed: 290, range: 150 },
    // Ловкость
    { name: 'Жрица Луны', title: 'Лучница ночи', attr: 'agility', role: 'damager', roleName: 'Дамагер', heroId: 'priestess', image: 'priestess', unique: true, wip: true },
    { name: 'Иллюзионист', title: 'Мастер обмана', attr: 'agility', role: 'damager', roleName: 'Дамагер', heroId: 'illusionist', image: 'illusionist',
      strBase: 17, strGain: 2, agiBase: 22, agiGain: 3, intBase: 13, intGain: 2,
      hp: 200, mp: 150, atk: 70, def: 4, atkSpeed: 1.7, hpRegen: 0.50, mpRegen: 0.01, speed: 320, range: 150 },
    { name: 'Мурлок', title: 'Подводный охотник', attr: 'agility', role: 'damager', roleName: 'Дамагер', heroId: 'murloc', image: 'murloc', wip: true,
      strBase: 16, strGain: 1.8, agiBase: 25, agiGain: 3.1, intBase: 14, intGain: 1.4,
      hp: null, mp: null, atk: null, def: null, atkSpeed: null, hpRegen: null, mpRegen: 0.01, speed: 310, range: 150 },
    { name: 'Самурай', title: 'Мастер меча', attr: 'agility', role: 'damager', roleName: 'Дамагер', heroId: 'samurai', image: 'samurai', wip: true,
      strBase: 17, strGain: 1.8, agiBase: 26, agiGain: 3.2, intBase: 15, intGain: 1.5,
      hp: null, mp: null, atk: null, def: null, atkSpeed: null, hpRegen: null, mpRegen: 0.01, speed: 310, range: 150 },
    { name: 'Мастер клинка', title: 'Элитный мечник', attr: 'agility', role: 'damager', roleName: 'Дамагер', heroId: 'blademaster', image: 'blademaster', wip: true,
      strBase: 18, strGain: 2, agiBase: 24, agiGain: 3.2, intBase: 16, intGain: 1.7,
      hp: null, mp: null, atk: null, def: null, atkSpeed: null, hpRegen: null, mpRegen: 0.01, speed: 320, range: 150 },
    { name: 'Охотник на демонов', title: 'Мститель', attr: 'agility', role: 'damager', roleName: 'Дамагер', heroId: 'demonhunter', image: 'demonhunter', unique: true, wip: true },
    { name: 'Лучница', title: 'Ледяная охотница', attr: 'agility', role: 'damager', roleName: 'Дамагер', heroId: 'drowranger', image: 'DarkRanger', wip: true,
      strBase: 20, strGain: 2.5, agiBase: 31, agiGain: 4, intBase: 18, intGain: 1.7,
      hp: null, mp: null, atk: null, def: null, atkSpeed: null, hpRegen: null, mpRegen: 0.01, speed: 300, range: 625 },
    { name: 'Теневой клинок', title: 'Убийца из тени', attr: 'agility', role: 'damager', roleName: 'Дамагер', heroId: 'shadowblade', image: 'shadowblade', unique: true, wip: true,
      strBase: 14, strGain: 1.5, agiBase: 28, agiGain: 3.6, intBase: 14, intGain: 1.3,
      hp: null, mp: null, atk: null, def: null, atkSpeed: null, hpRegen: null, mpRegen: 0.01, speed: 320, range: 128 },
    // Интеллект
    { name: 'Громовержец', title: 'Повелитель молний', attr: 'intelligence', role: 'support', roleName: 'Помощник', heroId: 'thunderer', image: 'thunderer',
      strBase: 24, strGain: 2, agiBase: 12, agiGain: 2, intBase: 24, intGain: 3,
      hp: 250, mp: 150, atk: 20, def: 1, atkSpeed: 2.25, hpRegen: 2, mpRegen: 0.01, speed: 280, range: 600 },
    { name: 'Повелитель Льдов', title: 'Маг холода', attr: 'intelligence', role: 'support', roleName: 'Помощник', heroId: 'icelord', image: 'icelord', wip: true,
      strBase: 16, strGain: 1.8, agiBase: 13, agiGain: 1.4, intBase: 24, intGain: 3.4,
      hp: null, mp: null, atk: null, def: null, atkSpeed: null, hpRegen: null, mpRegen: 0.01, speed: 270, range: 600 },
    { name: 'Архимаг', title: 'Маг воды', attr: 'intelligence', role: 'support', roleName: 'Помощник', heroId: 'archmage', image: 'Archmage', wip: true,
      strBase: 14, strGain: 1.5, agiBase: 17, agiGain: 1.6, intBase: 25, intGain: 3.5,
      hp: null, mp: null, atk: null, def: null, atkSpeed: null, hpRegen: null, mpRegen: 0.01, speed: 280, range: 600 },
    { name: 'Лич', title: 'Маг льда', attr: 'intelligence', role: 'support', roleName: 'Помощник', heroId: 'lich', image: 'lich', wip: true,
      strBase: 15, strGain: 2, agiBase: 14, agiGain: 1, intBase: 20, intGain: 3.4,
      hp: null, mp: null, atk: null, def: null, atkSpeed: null, hpRegen: null, mpRegen: 0.01, speed: 270, range: 500 },
    { name: 'Провидец', title: 'Шаман', attr: 'intelligence', role: 'support', roleName: 'Помощник', heroId: 'farseer', image: 'FarSeer', wip: true,
      strBase: 16, strGain: 2, agiBase: 15, agiGain: 1.5, intBase: 22, intGain: 3,
      hp: null, mp: null, atk: null, def: null, atkSpeed: null, hpRegen: null, mpRegen: 0.01, speed: 280, range: 600 },
    { name: 'Хранитель рощи', title: 'Друид', attr: 'intelligence', role: 'support', roleName: 'Помощник', heroId: 'keeper', image: 'keeper', wip: true,
      strBase: 17, strGain: 1.8, agiBase: 14, agiGain: 1.5, intBase: 22, intGain: 3.2,
      hp: null, mp: null, atk: null, def: null, atkSpeed: null, hpRegen: null, mpRegen: 0.01, speed: 280, range: 550 },
    { name: 'Хромомант', title: 'Повелитель времени', attr: 'intelligence', role: 'support', roleName: 'Помощник', heroId: 'chronomancer', image: 'chronomancer', unique: true, wip: true,
      strBase: 15, strGain: 1.6, agiBase: 16, agiGain: 1.8, intBase: 24, intGain: 3.2,
      hp: null, mp: null, atk: null, def: null, atkSpeed: null, hpRegen: null, mpRegen: 0.01, speed: 280, range: 550 },
    { name: 'Шаман крови', title: 'Запретная магия', attr: 'intelligence', role: 'support', roleName: 'Помощник', heroId: 'bloodshaman', image: 'bloodshaman', unique: true, wip: true,
      strBase: 20, strGain: 2.2, agiBase: 13, agiGain: 1.3, intBase: 22, intGain: 3,
      hp: null, mp: null, atk: null, def: null, atkSpeed: null, hpRegen: null, mpRegen: 0.01, speed: 275, range: 500 },
    { name: 'Некромант', title: 'Повелитель мёртвых', attr: 'intelligence', role: 'support', roleName: 'Поддержка', heroId: 'necromancer', image: 'necromancer', wip: true,
      strBase: 16, strGain: 1.8, agiBase: 14, agiGain: 1.5, intBase: 21, intGain: 3,
      hp: null, mp: null, atk: null, def: null, atkSpeed: null, hpRegen: null, mpRegen: 0.01, speed: 290, range: 600 },
];
